### ISSUE TITLE
Azure Sample Application - Containers

### ISSUE THREAD

**Issue by ThibaultBC** [bcgov/Cloud-Pathfinder-Azure#103]
Create a sample application that uses [Azure Container Services](https://learn.microsoft.com/en-us/azure/containers/) / [Azure Container App Environments (ACAE)](https://learn.microsoft.com/en-us/azure/container-apps/environment), as a reference example of how-to create the required infrastructure, and deploy a container into that environment.

Resources may include:
- Azure Container Registry (ACR)
- Azure Container App Environment (ACAE)
- Other resources TBD

## Acceptance Criteria
- [X] **Scenario: Container App Infrastructure**
  - An Azure Container Registry, and Azure Container App Environment are deployed in the same Resource Group
  - Required configurations/properties are either hard-coded, or set using variables
- [X] **Scenario: Deployment of the sample application onto the infrastructure**
  - Utilizing the infrastructure that was deployed, build/push container(s) to the Azure Container Registry
  - Once the container(s) are pushed to the Azure Container Registry, deploy the application onto the Azure Container App Environment

**Comment by AErmie** [comment]
- Code developed to deploy an Azure Container Registry, and Azure Container App Environment
- Sample application created, and successfully deploys into existing environment

Repo Link: https://github.com/bcgov/azure-startup-sample-app-containers

## Blockers
In order to deploy the Azure Container App Environment into a VNet, a Subnet with a `/21` or larger address space is required. Currently, within the **abc123** subscription, we cannot create a subnet without an NSG.

**Comment by AErmie** [comment]
- Updated `/examples/` directory, to accommodate future examples (ie. VNET integration)
  - Updated **Deploy Infra** pipeline to include selection for "example to deploy"
- Updated root **README** with explanation of example
- Created "**Workflow Extras**" pipeline to showcase additional tooling (ie. TFLint, Trivy, InfraCost)
