### ISSUE TITLE
Check GCPE - Interregnum rules on publishing Techdocs.

### ISSUE THREAD

**Issue by ThibaultBC** [bcgov/Cloud-Pathfinder-Azure#169]
1. Review PDF docs by GCPE on coms rules.
2. Define Tech Docs (is it "informational" vs. "statutory" vs. else - Does not apply?
3. Find who to ask and ask clearance to publish tech docs

**Comment by KhurrumBC** [comment]
1. PDF reviewed

2. Technical Documentation may be classified as informational documentation rather than purely internal operational documentation. This is because it is accessible to the public and could be seen as providing guidance or information about ministry processes.

3. The ministry's GCPE communication director must approve the distribution of any communication material during the campaign and interregnum.
